/*
 * Dropbox Sign API
 * Dropbox Sign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dropbox.sign.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.dropbox.sign.model.DataResidency;
import com.dropbox.sign.model.TeamSettingLock;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.dropbox.sign.JSON;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.ObjectMapper;


import com.dropbox.sign.ApiException;
/**
 * Updates the data residency team setting. Provide &#x60;value&#x60;, &#x60;lock_mode&#x60;, or both.
 */
@JsonPropertyOrder({
  DataResidencySettingUpdate.JSON_PROPERTY_VALUE,
  DataResidencySettingUpdate.JSON_PROPERTY_LOCK_MODE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
@JsonIgnoreProperties(ignoreUnknown=true)
public class DataResidencySettingUpdate {
  public static final String JSON_PROPERTY_VALUE = "value";
  @jakarta.annotation.Nullable
  private DataResidency value;

  public static final String JSON_PROPERTY_LOCK_MODE = "lock_mode";
  @jakarta.annotation.Nullable
  private TeamSettingLock lockMode;

  public DataResidencySettingUpdate() { 
  }

  /**
   * Attempt to instantiate and hydrate a new instance of this class
   * @param jsonData String of JSON data representing target object
   */
  static public DataResidencySettingUpdate init(String jsonData) throws Exception {
    return new ObjectMapper().readValue(jsonData, DataResidencySettingUpdate.class);
  }

  static public DataResidencySettingUpdate init(HashMap data) throws Exception {
    return new ObjectMapper().readValue(
      new ObjectMapper().writeValueAsString(data),
      DataResidencySettingUpdate.class
    );
  }

  public DataResidencySettingUpdate value(@jakarta.annotation.Nullable DataResidency value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DataResidency getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(@jakarta.annotation.Nullable DataResidency value) {
    this.value = value;
  }


  public DataResidencySettingUpdate lockMode(@jakarta.annotation.Nullable TeamSettingLock lockMode) {
    this.lockMode = lockMode;
    return this;
  }

  /**
   * Get lockMode
   * @return lockMode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCK_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TeamSettingLock getLockMode() {
    return lockMode;
  }


  @JsonProperty(JSON_PROPERTY_LOCK_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLockMode(@jakarta.annotation.Nullable TeamSettingLock lockMode) {
    this.lockMode = lockMode;
  }


  /**
   * Return true if this DataResidencySettingUpdate object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataResidencySettingUpdate dataResidencySettingUpdate = (DataResidencySettingUpdate) o;
    return Objects.equals(this.value, dataResidencySettingUpdate.value) &&
        Objects.equals(this.lockMode, dataResidencySettingUpdate.lockMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, lockMode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataResidencySettingUpdate {\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    lockMode: ").append(toIndentedString(lockMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  public Map<String, Object> createFormData() throws ApiException {
    Map<String, Object> map = new HashMap<>();
    boolean fileTypeFound = false;
    try {
    if (value != null) {
        if (isFileTypeOrListOfFiles(value)) {
            fileTypeFound = true;
        }

        if (value.getClass().equals(java.io.File.class) ||
            value.getClass().equals(Integer.class) ||
            value.getClass().equals(String.class) ||
            value.getClass().isEnum()) {
            map.put("value", value);
        } else if (isListOfFile(value)) {
            for(int i = 0; i< getListSize(value); i++) {
                map.put("value[" + i + "]", getFromList(value, i));
            }
        }
        else {
            map.put("value", JSON.getDefault().getMapper().writeValueAsString(value));
        }
    }
    if (lockMode != null) {
        if (isFileTypeOrListOfFiles(lockMode)) {
            fileTypeFound = true;
        }

        if (lockMode.getClass().equals(java.io.File.class) ||
            lockMode.getClass().equals(Integer.class) ||
            lockMode.getClass().equals(String.class) ||
            lockMode.getClass().isEnum()) {
            map.put("lock_mode", lockMode);
        } else if (isListOfFile(lockMode)) {
            for(int i = 0; i< getListSize(lockMode); i++) {
                map.put("lock_mode[" + i + "]", getFromList(lockMode, i));
            }
        }
        else {
            map.put("lock_mode", JSON.getDefault().getMapper().writeValueAsString(lockMode));
        }
    }
    } catch (Exception e) {
        throw new ApiException(e);
    }

    return fileTypeFound ? map : new HashMap<>();
  }

  private boolean isFileTypeOrListOfFiles(Object obj) throws Exception {
    return obj.getClass().equals(java.io.File.class) || isListOfFile(obj);
  }

  private boolean isListOfFile(Object obj) throws Exception {
      return obj instanceof java.util.List && !isListEmpty(obj) && getFromList(obj, 0) instanceof java.io.File;
  }

  private boolean isListEmpty(Object obj) throws Exception {
    return (boolean) Class.forName(java.util.List.class.getName()).getMethod("isEmpty").invoke(obj);
  }

  private Object getFromList(Object obj, int index) throws Exception {
    return Class.forName(java.util.List.class.getName()).getMethod("get", int.class).invoke(obj, index);
  }

  private int getListSize(Object obj) throws Exception {
    return (int) Class.forName(java.util.List.class.getName()).getMethod("size").invoke(obj);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

