# Need some of this config because we're using API Registry
organization: HelloSign
apis:
  hellosign-OAS@v1: 
    root: ./openapi.yaml

lint:
  extends:
    - recommended
  plugins:
    - 'bin/plugins/set-beta-plugin.js'
  decorators:
    hs-beta-fields/check-schema-for-beta-features: error
