# Need some of this config because we're using API Registry
apiDefinitions: 
  hellosign: ./openapi.yaml

lint:
  plugins:
    - 'bin/plugins/set-beta-plugin.js'
  extends:
    - recommended
  decorators:
    hs-beta-fields/check-schema-for-beta-features: error