# Note: this configuration is now set at a Portal level. 
# But, keeping this file here allows for testing Reference docs by themselves.

apiDefinitions:
  hellosign: ./openapi.yaml

lint:
  plugins:
    - './plugins/environment-plugin.js'
  decorators:
    environment/replace-servers-url: error

# Optimize performance for US customers
region: us

# NOTE: these settings are controlled by the documentation repo
# referenceDocs:

  
