# Need some of this config because we're using API Registry
apis: 
  HelloSign-OAS@v1:
    root: openapi.yaml
    decorators: 
      hs-decorators/add-custom-badge: 
        customBadge: "beta"
plugins:
  - 'bin/plugins/hs-custom-plugins.js'
extends:
  - recommended