# Need some of this config because we're using API Registry
organization: HelloSign
apis:
  hellosign@v1: 
    root: ./openapi.yaml

lint:
  extends:
    - recommended
  plugins:
    - 'bin/plugins/beta-fields-plugin.js'
  decorators:
    hs-beta-fields/check-request-schema-for-beta: error
