#!/usr/bin/env bash

set -e

DIR=$(cd `dirname $0` && pwd)
LANGUAGE="${1:-en}"

printf "Language chosen: ${LANGUAGE}\n"

printf "\nInstalling composer dependencies ...\n"
mkdir -p "${DIR}/vendor"
bash "${DIR}/bin/php" composer install
printf "\n"

bash "${DIR}/bin/php" ./bin/generate-oas.php

"${DIR}/bin/copy-examples-filtered" "${DIR}/examples" "${DIR}/sandbox/dotnet/src/Dropbox.SignSandbox" cs
"${DIR}/bin/copy-examples-filtered" "${DIR}/examples" "${DIR}/sandbox/java/src/main/java/com/dropbox/sign_sandbox" java
"${DIR}/bin/copy-examples-filtered" "${DIR}/examples" "${DIR}/sandbox/php/src" php
"${DIR}/bin/copy-examples-filtered" "${DIR}/examples" "${DIR}/sandbox/python/src" py
"${DIR}/bin/copy-examples-filtered" "${DIR}/examples" "${DIR}/sandbox/ruby/src" rb
"${DIR}/bin/copy-examples-filtered" "${DIR}/examples" "${DIR}/sandbox/node/src" ts

printf "Success!\n"
