#!/usr/bin/env bash

set -e

DIR=$(cd `dirname $0` && pwd)
LANGUAGE="${1:-en}"

printf "Language chosen: ${LANGUAGE}\n"

printf "\nInstalling composer dependencies ...\n"
mkdir -p "${DIR}/vendor"
bash "${DIR}/bin/php" composer install
printf "\n"

bash "${DIR}/bin/php" ./bin/generate-oas.php

cp "${DIR}/examples/"*.cs "${DIR}/sandbox/dotnet/src/Dropbox.SignSandbox/"
cp "${DIR}/examples/"*.java "${DIR}/sandbox/java/src/main/java/com/dropbox/sign_sandbox/"
cp "${DIR}/examples/"*.php "${DIR}/sandbox/php/src/"
cp "${DIR}/examples/"*.py "${DIR}/sandbox/python/src/"
cp "${DIR}/examples/"*.rb "${DIR}/sandbox/ruby/src/"
cp "${DIR}/examples/"*.ts "${DIR}/sandbox/node/src/"

printf "Success!\n"
