#!/usr/bin/env bash

set -e

DIR=$(cd `dirname $0` && pwd)
LANGUAGE="${1:-en}"

printf "Language chosen: ${LANGUAGE}\n"

printf "\nInstalling composer dependencies ...\n"
mkdir -p "${DIR}/vendor"
bash "${DIR}/bin/php" composer install
printf "\n"

printf "\nCreating translated OpenAPI file ...\n"
bash "${DIR}/bin/php" ./bin/generate-translated-oas.php
printf "\n"

printf "\nCreating SDK-specific OpenAPI file ...\n"
bash "${DIR}/bin/php" ./bin/generate-sdk-oas.php
printf "\n"

printf "Success!\n"
