#!/usr/bin/env bash

set -e

DIR=$(cd `dirname $0` && pwd)
SDKS=( dotnet java-v1 java-v2 node php python ruby )
SHOW_HELP=0
TARGET_SDK=
TESTING=0

while getopts ":t:h-:" opt; do
  case $opt in
    t) TARGET_SDK="$OPTARG"
    ;;
    h) SHOW_HELP=1
    ;;
    -)
      case "${OPTARG}" in
        testing) TESTING=1
        ;;
        *) echo "Invalid option --$OPTARG" >&2
        ;;
      esac
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

function main() {
  if [[ $SHOW_HELP -eq 1 ]]; then
    show_help

    exit 0
  fi

  if [[ -z ${TARGET_SDK} ]]; then
    show_help

    exit 0
  fi

  validate_sdk_choice $TARGET_SDK

  if [[ "${TARGET_SDK}" != "all" ]]; then
    build_sdk $TARGET_SDK
  else
    for SDK in "${SDKS[@]}"
    do :
      build_sdk $SDK
    done
  fi

  printf "Success! All SDKs built!\n"
  exit 0
}

function show_help() {
    cat << EOF
Usage: generate-sdks [OPTION]
Builds a given SDK into the sdks/[SDK] directory.

**WARNING** All files and directories present in the sdks/[SDK] directory will
            be DELETED and REBUILT!

-t          target SDK, "all", "dotnet", "java-v2", "java-v1", "node", "php", "python", "ruby"
--testing   use openapi-sdk-testing.yaml (includes all hideOn endpoints)
-h          display this help and exit
Example: generate-sdks -t php
Example: generate-sdks -t php --testing
EOF

    exit 0
}

function validate_sdk_choice()
{
  SDK="$1"

  if [[
    "${SDK}" != "all" &&
    "${SDK}" != "dotnet" &&
    "${SDK}" != "java-v1" &&
    "${SDK}" != "java-v2" &&
    "${SDK}" != "node" &&
    "${SDK}" != "php" &&
    "${SDK}" != "python" &&
    "${SDK}" != "ruby"
  ]]; then
    printf "Invalid SDK (-t) value: ${SDK}\n"
    show_help

    exit 1
  fi
}

function build_sdk()
{
  SDK="$1"
  SDK_DIR="${DIR}/sdks/${SDK}"

  printf "Building ${SDK} SDK\n"

  clear_previous_build_files $SDK
  copy_oas $SDK
  copy_examples $SDK
  copy_test_fixtures $SDK

  bash "${SDK_DIR}/run-build"

  printf "\n\n"
  printf "########\n"
  printf "######## Done building ${SDK} SDK\n"
  printf "########\n"
  printf "\n\n"
}

function clear_previous_build_files()
{
  SDK="$1"
  SDK_DIR="${DIR}/sdks/${SDK}"

  printf "Clearing previous build files ...\n"

  if [[ "${SDK}" == "dotnet" ]]; then
    rm -rf "${SDK_DIR}/docs"
    rm -rf "${SDK_DIR}/src/HelloSign"
  elif [[ "${SDK}" == "java-v2" || "${SDK}" == "java-v1" ]]; then
    rm -rf "${SDK_DIR}/docs"
    rm -rf "${SDK_DIR}/src/main"
  elif [[ "${SDK}" == "node" ]]; then
    rm -rf "${SDK_DIR}/api"
    rm -rf "${SDK_DIR}/dist"
    rm -rf "${SDK_DIR}/docs"
    rm -rf "${SDK_DIR}/model"
    rm -rf "${SDK_DIR}/types"
  elif [[ "${SDK}" == "php" ]]; then
    rm -rf "${SDK_DIR}/docs"
    rm -rf "${SDK_DIR}/src"
  elif [[ "${SDK}" == "python" ]]; then
    rm -rf "${SDK_DIR}/docs"
    rm -rf "${SDK_DIR}/hellosign_sdk"
  elif [[ "${SDK}" == "ruby" ]]; then
    rm -rf "${SDK_DIR}/docs"
    rm -rf "${SDK_DIR}/lib"
  fi
}

function copy_oas()
{
  SDK="$1"
  SDK_DIR="${DIR}/sdks/${SDK}"

  if [[ $TESTING -eq 1 ]]; then
    OAS_FILE="${DIR}/openapi-sdk-testing.yaml"
    printf "Copying openapi-sdk-testing.yaml ...\n"
  else
    OAS_FILE="${DIR}/openapi-sdk.yaml"
    printf "Copying openapi-sdk.yaml ...\n"
  fi

  rm -f "${SDK_DIR}/openapi-sdk.yaml"
  cp -r "${OAS_FILE}" "${SDK_DIR}/openapi-sdk.yaml"
}

function copy_examples()
{
  SDK="$1"
  SDK_DIR="${DIR}/sdks/${SDK}"

  printf "Copying examples ...\n"
  rm -rf "${SDK_DIR}/examples"
  mkdir -p "${SDK_DIR}/examples"

  if [[ "${SDK}" == "dotnet" ]]; then
    "${DIR}/bin/copy-examples-filtered" "${DIR}/sandbox/dotnet/src/Dropbox.SignSandbox" "${SDK_DIR}/examples" cs
  elif [[ "${SDK}" == "java-v2" || "${SDK}" == "java-v1" ]]; then
    "${DIR}/bin/copy-examples-filtered" "${DIR}/sandbox/java/src/main/java/com/dropbox/sign_sandbox" "${SDK_DIR}/examples" java
  elif [[ "${SDK}" == "node" ]]; then
    "${DIR}/bin/copy-examples-filtered" "${DIR}/sandbox/node/src" "${SDK_DIR}/examples" ts
  elif [[ "${SDK}" == "php" ]]; then
    "${DIR}/bin/copy-examples-filtered" "${DIR}/sandbox/php/src" "${SDK_DIR}/examples" php
  elif [[ "${SDK}" == "python" ]]; then
    "${DIR}/bin/copy-examples-filtered" "${DIR}/sandbox/python/src" "${SDK_DIR}/examples" py
  elif [[ "${SDK}" == "ruby" ]]; then
    "${DIR}/bin/copy-examples-filtered" "${DIR}/sandbox/ruby/src" "${SDK_DIR}/examples" rb
  fi
}

function copy_test_fixtures()
{
  SDK="$1"
  SDK_DIR="${DIR}/sdks/${SDK}"

  printf "Copying test_fixtures ...\n"
  rm -rf "${SDK_DIR}/test_fixtures"
  cp -r "${DIR}/test_fixtures" "${SDK_DIR}/test_fixtures"
}

main
