=begin
#Dropbox Sign API

#Dropbox Sign v3 API

The version of the OpenAPI document: 3.0.0
Contact: apisupport@hellosign.com
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'date'
require 'time'

module Dropbox
end

module Dropbox::Sign
  class FaxLineAreaCodeGetProvinceEnum
    AB = "AB".freeze
    BC = "BC".freeze
    MB = "MB".freeze
    NB = "NB".freeze
    NL = "NL".freeze
    NT = "NT".freeze
    NS = "NS".freeze
    NU = "NU".freeze
    ON = "ON".freeze
    PE = "PE".freeze
    QC = "QC".freeze
    SK = "SK".freeze
    YT = "YT".freeze

    def self.all_vars
      @all_vars ||= [AB, BC, MB, NB, NL, NT, NS, NU, ON, PE, QC, SK, YT].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if FaxLineAreaCodeGetProvinceEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #FaxLineAreaCodeGetProvinceEnum"
    end
  end
end
