<?php
/**
 * AccountSettingsUpdateRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @see     https://openapi-generator.tech
 */

/**
 * Dropbox Sign API
 *
 * Dropbox Sign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dropbox\Sign\Model;

use ArrayAccess;
use Dropbox\Sign\ObjectSerializer;
use InvalidArgumentException;
use JsonSerializable;
use ReturnTypeWillChange;

/**
 * AccountSettingsUpdateRequest Class Doc Comment
 *
 * @category Class
 * @see     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class AccountSettingsUpdateRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'AccountSettingsUpdateRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'company' => 'string',
        'custom_signing_redirect_enabled' => 'bool',
        'custom_signing_redirect_url' => 'string',
        'custom_tagline' => 'string',
        'date_format' => '\Dropbox\Sign\Model\DateFormat',
        'is_signature_reminders_enabled' => 'bool',
        'request_email_from' => 'string',
        'request_email_signature' => 'string',
        'required_signature_types' => '\Dropbox\Sign\Model\RequiredSignatureType[]',
        'should_enable_tamper_proof' => 'bool',
        'should_include_distinct_pdfs' => 'bool',
        'should_offer_signer_access_code' => 'bool',
        'should_offer_signer_sms_authentication' => 'bool',
        'should_remove_document_id' => 'bool',
        'is_notify_on_sign_enabled' => 'bool',
        'is_notify_on_view_enabled' => 'bool',
        'should_autocomplete' => 'bool',
        'should_include_requested_pdfs' => 'bool',
        'should_include_requested_pdfs_for_others' => 'bool',
        'should_include_sent_doc_pdfs' => 'bool',
        'should_include_sent_doc_pdfs_for_others' => 'bool',
        'should_send_daily_summary' => 'bool',
        'should_send_embedded_signature_conf_emails' => 'bool',
        'should_send_ordered_sr_email' => 'bool',
        'should_send_outbound_conf_emails' => 'bool',
        'template_link_signature_emails_enabled' => 'bool',
        'unset' => 'string[]',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'company' => null,
        'custom_signing_redirect_enabled' => null,
        'custom_signing_redirect_url' => null,
        'custom_tagline' => null,
        'date_format' => null,
        'is_signature_reminders_enabled' => null,
        'request_email_from' => null,
        'request_email_signature' => null,
        'required_signature_types' => null,
        'should_enable_tamper_proof' => null,
        'should_include_distinct_pdfs' => null,
        'should_offer_signer_access_code' => null,
        'should_offer_signer_sms_authentication' => null,
        'should_remove_document_id' => null,
        'is_notify_on_sign_enabled' => null,
        'is_notify_on_view_enabled' => null,
        'should_autocomplete' => null,
        'should_include_requested_pdfs' => null,
        'should_include_requested_pdfs_for_others' => null,
        'should_include_sent_doc_pdfs' => null,
        'should_include_sent_doc_pdfs_for_others' => null,
        'should_send_daily_summary' => null,
        'should_send_embedded_signature_conf_emails' => null,
        'should_send_ordered_sr_email' => null,
        'should_send_outbound_conf_emails' => null,
        'template_link_signature_emails_enabled' => null,
        'unset' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'company' => false,
        'custom_signing_redirect_enabled' => false,
        'custom_signing_redirect_url' => false,
        'custom_tagline' => false,
        'date_format' => false,
        'is_signature_reminders_enabled' => false,
        'request_email_from' => false,
        'request_email_signature' => false,
        'required_signature_types' => false,
        'should_enable_tamper_proof' => false,
        'should_include_distinct_pdfs' => false,
        'should_offer_signer_access_code' => false,
        'should_offer_signer_sms_authentication' => false,
        'should_remove_document_id' => false,
        'is_notify_on_sign_enabled' => false,
        'is_notify_on_view_enabled' => false,
        'should_autocomplete' => false,
        'should_include_requested_pdfs' => false,
        'should_include_requested_pdfs_for_others' => false,
        'should_include_sent_doc_pdfs' => false,
        'should_include_sent_doc_pdfs_for_others' => false,
        'should_send_daily_summary' => false,
        'should_send_embedded_signature_conf_emails' => false,
        'should_send_ordered_sr_email' => false,
        'should_send_outbound_conf_emails' => false,
        'template_link_signature_emails_enabled' => false,
        'unset' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'company' => 'company',
        'custom_signing_redirect_enabled' => 'custom_signing_redirect_enabled',
        'custom_signing_redirect_url' => 'custom_signing_redirect_url',
        'custom_tagline' => 'custom_tagline',
        'date_format' => 'date_format',
        'is_signature_reminders_enabled' => 'is_signature_reminders_enabled',
        'request_email_from' => 'request_email_from',
        'request_email_signature' => 'request_email_signature',
        'required_signature_types' => 'required_signature_types',
        'should_enable_tamper_proof' => 'should_enable_tamper_proof',
        'should_include_distinct_pdfs' => 'should_include_distinct_pdfs',
        'should_offer_signer_access_code' => 'should_offer_signer_access_code',
        'should_offer_signer_sms_authentication' => 'should_offer_signer_sms_authentication',
        'should_remove_document_id' => 'should_remove_document_id',
        'is_notify_on_sign_enabled' => 'is_notify_on_sign_enabled',
        'is_notify_on_view_enabled' => 'is_notify_on_view_enabled',
        'should_autocomplete' => 'should_autocomplete',
        'should_include_requested_pdfs' => 'should_include_requested_pdfs',
        'should_include_requested_pdfs_for_others' => 'should_include_requested_pdfs_for_others',
        'should_include_sent_doc_pdfs' => 'should_include_sent_doc_pdfs',
        'should_include_sent_doc_pdfs_for_others' => 'should_include_sent_doc_pdfs_for_others',
        'should_send_daily_summary' => 'should_send_daily_summary',
        'should_send_embedded_signature_conf_emails' => 'should_send_embedded_signature_conf_emails',
        'should_send_ordered_sr_email' => 'should_send_ordered_sr_email',
        'should_send_outbound_conf_emails' => 'should_send_outbound_conf_emails',
        'template_link_signature_emails_enabled' => 'template_link_signature_emails_enabled',
        'unset' => 'unset',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'company' => 'setCompany',
        'custom_signing_redirect_enabled' => 'setCustomSigningRedirectEnabled',
        'custom_signing_redirect_url' => 'setCustomSigningRedirectUrl',
        'custom_tagline' => 'setCustomTagline',
        'date_format' => 'setDateFormat',
        'is_signature_reminders_enabled' => 'setIsSignatureRemindersEnabled',
        'request_email_from' => 'setRequestEmailFrom',
        'request_email_signature' => 'setRequestEmailSignature',
        'required_signature_types' => 'setRequiredSignatureTypes',
        'should_enable_tamper_proof' => 'setShouldEnableTamperProof',
        'should_include_distinct_pdfs' => 'setShouldIncludeDistinctPdfs',
        'should_offer_signer_access_code' => 'setShouldOfferSignerAccessCode',
        'should_offer_signer_sms_authentication' => 'setShouldOfferSignerSmsAuthentication',
        'should_remove_document_id' => 'setShouldRemoveDocumentId',
        'is_notify_on_sign_enabled' => 'setIsNotifyOnSignEnabled',
        'is_notify_on_view_enabled' => 'setIsNotifyOnViewEnabled',
        'should_autocomplete' => 'setShouldAutocomplete',
        'should_include_requested_pdfs' => 'setShouldIncludeRequestedPdfs',
        'should_include_requested_pdfs_for_others' => 'setShouldIncludeRequestedPdfsForOthers',
        'should_include_sent_doc_pdfs' => 'setShouldIncludeSentDocPdfs',
        'should_include_sent_doc_pdfs_for_others' => 'setShouldIncludeSentDocPdfsForOthers',
        'should_send_daily_summary' => 'setShouldSendDailySummary',
        'should_send_embedded_signature_conf_emails' => 'setShouldSendEmbeddedSignatureConfEmails',
        'should_send_ordered_sr_email' => 'setShouldSendOrderedSrEmail',
        'should_send_outbound_conf_emails' => 'setShouldSendOutboundConfEmails',
        'template_link_signature_emails_enabled' => 'setTemplateLinkSignatureEmailsEnabled',
        'unset' => 'setUnset',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'company' => 'getCompany',
        'custom_signing_redirect_enabled' => 'getCustomSigningRedirectEnabled',
        'custom_signing_redirect_url' => 'getCustomSigningRedirectUrl',
        'custom_tagline' => 'getCustomTagline',
        'date_format' => 'getDateFormat',
        'is_signature_reminders_enabled' => 'getIsSignatureRemindersEnabled',
        'request_email_from' => 'getRequestEmailFrom',
        'request_email_signature' => 'getRequestEmailSignature',
        'required_signature_types' => 'getRequiredSignatureTypes',
        'should_enable_tamper_proof' => 'getShouldEnableTamperProof',
        'should_include_distinct_pdfs' => 'getShouldIncludeDistinctPdfs',
        'should_offer_signer_access_code' => 'getShouldOfferSignerAccessCode',
        'should_offer_signer_sms_authentication' => 'getShouldOfferSignerSmsAuthentication',
        'should_remove_document_id' => 'getShouldRemoveDocumentId',
        'is_notify_on_sign_enabled' => 'getIsNotifyOnSignEnabled',
        'is_notify_on_view_enabled' => 'getIsNotifyOnViewEnabled',
        'should_autocomplete' => 'getShouldAutocomplete',
        'should_include_requested_pdfs' => 'getShouldIncludeRequestedPdfs',
        'should_include_requested_pdfs_for_others' => 'getShouldIncludeRequestedPdfsForOthers',
        'should_include_sent_doc_pdfs' => 'getShouldIncludeSentDocPdfs',
        'should_include_sent_doc_pdfs_for_others' => 'getShouldIncludeSentDocPdfsForOthers',
        'should_send_daily_summary' => 'getShouldSendDailySummary',
        'should_send_embedded_signature_conf_emails' => 'getShouldSendEmbeddedSignatureConfEmails',
        'should_send_ordered_sr_email' => 'getShouldSendOrderedSrEmail',
        'should_send_outbound_conf_emails' => 'getShouldSendOutboundConfEmails',
        'template_link_signature_emails_enabled' => 'getTemplateLinkSignatureEmailsEnabled',
        'unset' => 'getUnset',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const MODEL_UNSET_COMPANY = 'company';
    public const MODEL_UNSET_CUSTOM_SIGNING_REDIRECT_ENABLED = 'custom_signing_redirect_enabled';
    public const MODEL_UNSET_CUSTOM_SIGNING_REDIRECT_URL = 'custom_signing_redirect_url';
    public const MODEL_UNSET_CUSTOM_TAGLINE = 'custom_tagline';
    public const MODEL_UNSET_DATE_FORMAT = 'date_format';
    public const MODEL_UNSET_IS_SIGNATURE_REMINDERS_ENABLED = 'is_signature_reminders_enabled';
    public const MODEL_UNSET_REQUEST_EMAIL_FROM = 'request_email_from';
    public const MODEL_UNSET_REQUEST_EMAIL_SIGNATURE = 'request_email_signature';
    public const MODEL_UNSET_REQUIRED_SIGNATURE_TYPES = 'required_signature_types';
    public const MODEL_UNSET_SHOULD_ENABLE_TAMPER_PROOF = 'should_enable_tamper_proof';
    public const MODEL_UNSET_SHOULD_INCLUDE_DISTINCT_PDFS = 'should_include_distinct_pdfs';
    public const MODEL_UNSET_SHOULD_OFFER_SIGNER_ACCESS_CODE = 'should_offer_signer_access_code';
    public const MODEL_UNSET_SHOULD_OFFER_SIGNER_SMS_AUTHENTICATION = 'should_offer_signer_sms_authentication';
    public const MODEL_UNSET_SHOULD_REMOVE_DOCUMENT_ID = 'should_remove_document_id';
    public const MODEL_UNSET_IS_NOTIFY_ON_SIGN_ENABLED = 'is_notify_on_sign_enabled';
    public const MODEL_UNSET_IS_NOTIFY_ON_VIEW_ENABLED = 'is_notify_on_view_enabled';
    public const MODEL_UNSET_SHOULD_AUTOCOMPLETE = 'should_autocomplete';
    public const MODEL_UNSET_SHOULD_INCLUDE_REQUESTED_PDFS = 'should_include_requested_pdfs';
    public const MODEL_UNSET_SHOULD_INCLUDE_REQUESTED_PDFS_FOR_OTHERS = 'should_include_requested_pdfs_for_others';
    public const MODEL_UNSET_SHOULD_INCLUDE_SENT_DOC_PDFS = 'should_include_sent_doc_pdfs';
    public const MODEL_UNSET_SHOULD_INCLUDE_SENT_DOC_PDFS_FOR_OTHERS = 'should_include_sent_doc_pdfs_for_others';
    public const MODEL_UNSET_SHOULD_SEND_DAILY_SUMMARY = 'should_send_daily_summary';
    public const MODEL_UNSET_SHOULD_SEND_EMBEDDED_SIGNATURE_CONF_EMAILS = 'should_send_embedded_signature_conf_emails';
    public const MODEL_UNSET_SHOULD_SEND_ORDERED_SR_EMAIL = 'should_send_ordered_sr_email';
    public const MODEL_UNSET_SHOULD_SEND_OUTBOUND_CONF_EMAILS = 'should_send_outbound_conf_emails';
    public const MODEL_UNSET_TEMPLATE_LINK_SIGNATURE_EMAILS_ENABLED = 'template_link_signature_emails_enabled';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getUnsetAllowableValues()
    {
        return [
            self::MODEL_UNSET_COMPANY,
            self::MODEL_UNSET_CUSTOM_SIGNING_REDIRECT_ENABLED,
            self::MODEL_UNSET_CUSTOM_SIGNING_REDIRECT_URL,
            self::MODEL_UNSET_CUSTOM_TAGLINE,
            self::MODEL_UNSET_DATE_FORMAT,
            self::MODEL_UNSET_IS_SIGNATURE_REMINDERS_ENABLED,
            self::MODEL_UNSET_REQUEST_EMAIL_FROM,
            self::MODEL_UNSET_REQUEST_EMAIL_SIGNATURE,
            self::MODEL_UNSET_REQUIRED_SIGNATURE_TYPES,
            self::MODEL_UNSET_SHOULD_ENABLE_TAMPER_PROOF,
            self::MODEL_UNSET_SHOULD_INCLUDE_DISTINCT_PDFS,
            self::MODEL_UNSET_SHOULD_OFFER_SIGNER_ACCESS_CODE,
            self::MODEL_UNSET_SHOULD_OFFER_SIGNER_SMS_AUTHENTICATION,
            self::MODEL_UNSET_SHOULD_REMOVE_DOCUMENT_ID,
            self::MODEL_UNSET_IS_NOTIFY_ON_SIGN_ENABLED,
            self::MODEL_UNSET_IS_NOTIFY_ON_VIEW_ENABLED,
            self::MODEL_UNSET_SHOULD_AUTOCOMPLETE,
            self::MODEL_UNSET_SHOULD_INCLUDE_REQUESTED_PDFS,
            self::MODEL_UNSET_SHOULD_INCLUDE_REQUESTED_PDFS_FOR_OTHERS,
            self::MODEL_UNSET_SHOULD_INCLUDE_SENT_DOC_PDFS,
            self::MODEL_UNSET_SHOULD_INCLUDE_SENT_DOC_PDFS_FOR_OTHERS,
            self::MODEL_UNSET_SHOULD_SEND_DAILY_SUMMARY,
            self::MODEL_UNSET_SHOULD_SEND_EMBEDDED_SIGNATURE_CONF_EMAILS,
            self::MODEL_UNSET_SHOULD_SEND_ORDERED_SR_EMAIL,
            self::MODEL_UNSET_SHOULD_SEND_OUTBOUND_CONF_EMAILS,
            self::MODEL_UNSET_TEMPLATE_LINK_SIGNATURE_EMAILS_ENABLED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                           initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('company', $data ?? [], null);
        $this->setIfExists('custom_signing_redirect_enabled', $data ?? [], null);
        $this->setIfExists('custom_signing_redirect_url', $data ?? [], null);
        $this->setIfExists('custom_tagline', $data ?? [], null);
        $this->setIfExists('date_format', $data ?? [], null);
        $this->setIfExists('is_signature_reminders_enabled', $data ?? [], null);
        $this->setIfExists('request_email_from', $data ?? [], null);
        $this->setIfExists('request_email_signature', $data ?? [], null);
        $this->setIfExists('required_signature_types', $data ?? [], null);
        $this->setIfExists('should_enable_tamper_proof', $data ?? [], null);
        $this->setIfExists('should_include_distinct_pdfs', $data ?? [], null);
        $this->setIfExists('should_offer_signer_access_code', $data ?? [], null);
        $this->setIfExists('should_offer_signer_sms_authentication', $data ?? [], null);
        $this->setIfExists('should_remove_document_id', $data ?? [], null);
        $this->setIfExists('is_notify_on_sign_enabled', $data ?? [], null);
        $this->setIfExists('is_notify_on_view_enabled', $data ?? [], null);
        $this->setIfExists('should_autocomplete', $data ?? [], null);
        $this->setIfExists('should_include_requested_pdfs', $data ?? [], null);
        $this->setIfExists('should_include_requested_pdfs_for_others', $data ?? [], null);
        $this->setIfExists('should_include_sent_doc_pdfs', $data ?? [], null);
        $this->setIfExists('should_include_sent_doc_pdfs_for_others', $data ?? [], null);
        $this->setIfExists('should_send_daily_summary', $data ?? [], null);
        $this->setIfExists('should_send_embedded_signature_conf_emails', $data ?? [], null);
        $this->setIfExists('should_send_ordered_sr_email', $data ?? [], null);
        $this->setIfExists('should_send_outbound_conf_emails', $data ?? [], null);
        $this->setIfExists('template_link_signature_emails_enabled', $data ?? [], null);
        $this->setIfExists('unset', $data ?? [], null);
    }

    /**
     * @deprecated use ::init()
     */
    public static function fromArray(array $data): AccountSettingsUpdateRequest
    {
        return self::init($data);
    }

    /**
     * Attempt to instantiate and hydrate a new instance of this class
     */
    public static function init(array $data): AccountSettingsUpdateRequest
    {
        /** @var AccountSettingsUpdateRequest */
        return ObjectSerializer::deserialize(
            $data,
            AccountSettingsUpdateRequest::class,
        );
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string|int|object|array|mixed $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        return [];
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets company
     *
     * @return string|null
     */
    public function getCompany()
    {
        return $this->container['company'];
    }

    /**
     * Sets company
     *
     * @param string|null $company company name associated with this account or team
     *
     * @return self
     */
    public function setCompany(?string $company)
    {
        if (is_null($company)) {
            throw new InvalidArgumentException('non-nullable company cannot be null');
        }
        $this->container['company'] = $company;

        return $this;
    }

    /**
     * Gets custom_signing_redirect_enabled
     *
     * @return bool|null
     */
    public function getCustomSigningRedirectEnabled()
    {
        return $this->container['custom_signing_redirect_enabled'];
    }

    /**
     * Sets custom_signing_redirect_enabled
     *
     * @param bool|null $custom_signing_redirect_enabled whether signers are redirected to a custom URL after completing a signature request
     *
     * @return self
     */
    public function setCustomSigningRedirectEnabled(?bool $custom_signing_redirect_enabled)
    {
        if (is_null($custom_signing_redirect_enabled)) {
            throw new InvalidArgumentException('non-nullable custom_signing_redirect_enabled cannot be null');
        }
        $this->container['custom_signing_redirect_enabled'] = $custom_signing_redirect_enabled;

        return $this;
    }

    /**
     * Gets custom_signing_redirect_url
     *
     * @return string|null
     */
    public function getCustomSigningRedirectUrl()
    {
        return $this->container['custom_signing_redirect_url'];
    }

    /**
     * Sets custom_signing_redirect_url
     *
     * @param string|null $custom_signing_redirect_url URL where signers are redirected after completing a signature request when custom redirects are enabled
     *
     * @return self
     */
    public function setCustomSigningRedirectUrl(?string $custom_signing_redirect_url)
    {
        if (is_null($custom_signing_redirect_url)) {
            throw new InvalidArgumentException('non-nullable custom_signing_redirect_url cannot be null');
        }
        $this->container['custom_signing_redirect_url'] = $custom_signing_redirect_url;

        return $this;
    }

    /**
     * Gets custom_tagline
     *
     * @return string|null
     */
    public function getCustomTagline()
    {
        return $this->container['custom_tagline'];
    }

    /**
     * Sets custom_tagline
     *
     * @param string|null $custom_tagline custom tagline displayed with the account or team branding
     *
     * @return self
     */
    public function setCustomTagline(?string $custom_tagline)
    {
        if (is_null($custom_tagline)) {
            throw new InvalidArgumentException('non-nullable custom_tagline cannot be null');
        }
        $this->container['custom_tagline'] = $custom_tagline;

        return $this;
    }

    /**
     * Gets date_format
     *
     * @return DateFormat|null
     */
    public function getDateFormat()
    {
        return $this->container['date_format'];
    }

    /**
     * Sets date_format
     *
     * @param DateFormat|null $date_format date_format
     *
     * @return self
     */
    public function setDateFormat(?DateFormat $date_format)
    {
        if (is_null($date_format)) {
            throw new InvalidArgumentException('non-nullable date_format cannot be null');
        }
        $this->container['date_format'] = $date_format;

        return $this;
    }

    /**
     * Gets is_signature_reminders_enabled
     *
     * @return bool|null
     */
    public function getIsSignatureRemindersEnabled()
    {
        return $this->container['is_signature_reminders_enabled'];
    }

    /**
     * Sets is_signature_reminders_enabled
     *
     * @param bool|null $is_signature_reminders_enabled whether automatic reminder emails are enabled for incomplete signature requests
     *
     * @return self
     */
    public function setIsSignatureRemindersEnabled(?bool $is_signature_reminders_enabled)
    {
        if (is_null($is_signature_reminders_enabled)) {
            throw new InvalidArgumentException('non-nullable is_signature_reminders_enabled cannot be null');
        }
        $this->container['is_signature_reminders_enabled'] = $is_signature_reminders_enabled;

        return $this;
    }

    /**
     * Gets request_email_from
     *
     * @return string|null
     */
    public function getRequestEmailFrom()
    {
        return $this->container['request_email_from'];
    }

    /**
     * Sets request_email_from
     *
     * @param string|null $request_email_from sender name shown on signature request emails
     *
     * @return self
     */
    public function setRequestEmailFrom(?string $request_email_from)
    {
        if (is_null($request_email_from)) {
            throw new InvalidArgumentException('non-nullable request_email_from cannot be null');
        }
        $this->container['request_email_from'] = $request_email_from;

        return $this;
    }

    /**
     * Gets request_email_signature
     *
     * @return string|null
     */
    public function getRequestEmailSignature()
    {
        return $this->container['request_email_signature'];
    }

    /**
     * Sets request_email_signature
     *
     * @param string|null $request_email_signature signature appended to signature request emails
     *
     * @return self
     */
    public function setRequestEmailSignature(?string $request_email_signature)
    {
        if (is_null($request_email_signature)) {
            throw new InvalidArgumentException('non-nullable request_email_signature cannot be null');
        }
        $this->container['request_email_signature'] = $request_email_signature;

        return $this;
    }

    /**
     * Gets required_signature_types
     *
     * @return RequiredSignatureType[]|null
     */
    public function getRequiredSignatureTypes()
    {
        return $this->container['required_signature_types'];
    }

    /**
     * Sets required_signature_types
     *
     * @param RequiredSignatureType[]|null $required_signature_types signature creation methods signers may use
     *
     * @return self
     */
    public function setRequiredSignatureTypes(?array $required_signature_types)
    {
        if (is_null($required_signature_types)) {
            throw new InvalidArgumentException('non-nullable required_signature_types cannot be null');
        }

        $this->container['required_signature_types'] = $required_signature_types;

        return $this;
    }

    /**
     * Gets should_enable_tamper_proof
     *
     * @return bool|null
     */
    public function getShouldEnableTamperProof()
    {
        return $this->container['should_enable_tamper_proof'];
    }

    /**
     * Sets should_enable_tamper_proof
     *
     * @param bool|null $should_enable_tamper_proof whether completed documents include a digital tamper-proof seal
     *
     * @return self
     */
    public function setShouldEnableTamperProof(?bool $should_enable_tamper_proof)
    {
        if (is_null($should_enable_tamper_proof)) {
            throw new InvalidArgumentException('non-nullable should_enable_tamper_proof cannot be null');
        }
        $this->container['should_enable_tamper_proof'] = $should_enable_tamper_proof;

        return $this;
    }

    /**
     * Gets should_include_distinct_pdfs
     *
     * @return bool|null
     */
    public function getShouldIncludeDistinctPdfs()
    {
        return $this->container['should_include_distinct_pdfs'];
    }

    /**
     * Sets should_include_distinct_pdfs
     *
     * @param bool|null $should_include_distinct_pdfs whether completed documents remain as separate PDF files instead of being merged into one PDF
     *
     * @return self
     */
    public function setShouldIncludeDistinctPdfs(?bool $should_include_distinct_pdfs)
    {
        if (is_null($should_include_distinct_pdfs)) {
            throw new InvalidArgumentException('non-nullable should_include_distinct_pdfs cannot be null');
        }
        $this->container['should_include_distinct_pdfs'] = $should_include_distinct_pdfs;

        return $this;
    }

    /**
     * Gets should_offer_signer_access_code
     *
     * @return bool|null
     */
    public function getShouldOfferSignerAccessCode()
    {
        return $this->container['should_offer_signer_access_code'];
    }

    /**
     * Sets should_offer_signer_access_code
     *
     * @param bool|null $should_offer_signer_access_code whether senders can require an access code to verify a signer
     *
     * @return self
     */
    public function setShouldOfferSignerAccessCode(?bool $should_offer_signer_access_code)
    {
        if (is_null($should_offer_signer_access_code)) {
            throw new InvalidArgumentException('non-nullable should_offer_signer_access_code cannot be null');
        }
        $this->container['should_offer_signer_access_code'] = $should_offer_signer_access_code;

        return $this;
    }

    /**
     * Gets should_offer_signer_sms_authentication
     *
     * @return bool|null
     */
    public function getShouldOfferSignerSmsAuthentication()
    {
        return $this->container['should_offer_signer_sms_authentication'];
    }

    /**
     * Sets should_offer_signer_sms_authentication
     *
     * @param bool|null $should_offer_signer_sms_authentication whether senders can require SMS authentication to verify a signer
     *
     * @return self
     */
    public function setShouldOfferSignerSmsAuthentication(?bool $should_offer_signer_sms_authentication)
    {
        if (is_null($should_offer_signer_sms_authentication)) {
            throw new InvalidArgumentException('non-nullable should_offer_signer_sms_authentication cannot be null');
        }
        $this->container['should_offer_signer_sms_authentication'] = $should_offer_signer_sms_authentication;

        return $this;
    }

    /**
     * Gets should_remove_document_id
     *
     * @return bool|null
     */
    public function getShouldRemoveDocumentId()
    {
        return $this->container['should_remove_document_id'];
    }

    /**
     * Sets should_remove_document_id
     *
     * @param bool|null $should_remove_document_id whether the Dropbox Sign document ID is hidden on sent documents
     *
     * @return self
     */
    public function setShouldRemoveDocumentId(?bool $should_remove_document_id)
    {
        if (is_null($should_remove_document_id)) {
            throw new InvalidArgumentException('non-nullable should_remove_document_id cannot be null');
        }
        $this->container['should_remove_document_id'] = $should_remove_document_id;

        return $this;
    }

    /**
     * Gets is_notify_on_sign_enabled
     *
     * @return bool|null
     */
    public function getIsNotifyOnSignEnabled()
    {
        return $this->container['is_notify_on_sign_enabled'];
    }

    /**
     * Sets is_notify_on_sign_enabled
     *
     * @param bool|null $is_notify_on_sign_enabled whether to notify the account when someone signs a document it sent
     *
     * @return self
     */
    public function setIsNotifyOnSignEnabled(?bool $is_notify_on_sign_enabled)
    {
        if (is_null($is_notify_on_sign_enabled)) {
            throw new InvalidArgumentException('non-nullable is_notify_on_sign_enabled cannot be null');
        }
        $this->container['is_notify_on_sign_enabled'] = $is_notify_on_sign_enabled;

        return $this;
    }

    /**
     * Gets is_notify_on_view_enabled
     *
     * @return bool|null
     */
    public function getIsNotifyOnViewEnabled()
    {
        return $this->container['is_notify_on_view_enabled'];
    }

    /**
     * Sets is_notify_on_view_enabled
     *
     * @param bool|null $is_notify_on_view_enabled whether to notify the account when someone opens a document it sent
     *
     * @return self
     */
    public function setIsNotifyOnViewEnabled(?bool $is_notify_on_view_enabled)
    {
        if (is_null($is_notify_on_view_enabled)) {
            throw new InvalidArgumentException('non-nullable is_notify_on_view_enabled cannot be null');
        }
        $this->container['is_notify_on_view_enabled'] = $is_notify_on_view_enabled;

        return $this;
    }

    /**
     * Gets should_autocomplete
     *
     * @return bool|null
     */
    public function getShouldAutocomplete()
    {
        return $this->container['should_autocomplete'];
    }

    /**
     * Sets should_autocomplete
     *
     * @param bool|null $should_autocomplete whether values entered in text fields are saved and suggested for future signature requests
     *
     * @return self
     */
    public function setShouldAutocomplete(?bool $should_autocomplete)
    {
        if (is_null($should_autocomplete)) {
            throw new InvalidArgumentException('non-nullable should_autocomplete cannot be null');
        }
        $this->container['should_autocomplete'] = $should_autocomplete;

        return $this;
    }

    /**
     * Gets should_include_requested_pdfs
     *
     * @return bool|null
     */
    public function getShouldIncludeRequestedPdfs()
    {
        return $this->container['should_include_requested_pdfs'];
    }

    /**
     * Sets should_include_requested_pdfs
     *
     * @param bool|null $should_include_requested_pdfs whether completed signature requests include PDF copies in emails sent to the account
     *
     * @return self
     */
    public function setShouldIncludeRequestedPdfs(?bool $should_include_requested_pdfs)
    {
        if (is_null($should_include_requested_pdfs)) {
            throw new InvalidArgumentException('non-nullable should_include_requested_pdfs cannot be null');
        }
        $this->container['should_include_requested_pdfs'] = $should_include_requested_pdfs;

        return $this;
    }

    /**
     * Gets should_include_requested_pdfs_for_others
     *
     * @return bool|null
     */
    public function getShouldIncludeRequestedPdfsForOthers()
    {
        return $this->container['should_include_requested_pdfs_for_others'];
    }

    /**
     * Sets should_include_requested_pdfs_for_others
     *
     * @param bool|null $should_include_requested_pdfs_for_others whether completed signature requests include PDF copies in emails sent to signers and CC recipients
     *
     * @return self
     */
    public function setShouldIncludeRequestedPdfsForOthers(?bool $should_include_requested_pdfs_for_others)
    {
        if (is_null($should_include_requested_pdfs_for_others)) {
            throw new InvalidArgumentException('non-nullable should_include_requested_pdfs_for_others cannot be null');
        }
        $this->container['should_include_requested_pdfs_for_others'] = $should_include_requested_pdfs_for_others;

        return $this;
    }

    /**
     * Gets should_include_sent_doc_pdfs
     *
     * @return bool|null
     */
    public function getShouldIncludeSentDocPdfs()
    {
        return $this->container['should_include_sent_doc_pdfs'];
    }

    /**
     * Sets should_include_sent_doc_pdfs
     *
     * @param bool|null $should_include_sent_doc_pdfs whether emails sent to the account include PDF copies of documents it sends
     *
     * @return self
     */
    public function setShouldIncludeSentDocPdfs(?bool $should_include_sent_doc_pdfs)
    {
        if (is_null($should_include_sent_doc_pdfs)) {
            throw new InvalidArgumentException('non-nullable should_include_sent_doc_pdfs cannot be null');
        }
        $this->container['should_include_sent_doc_pdfs'] = $should_include_sent_doc_pdfs;

        return $this;
    }

    /**
     * Gets should_include_sent_doc_pdfs_for_others
     *
     * @return bool|null
     */
    public function getShouldIncludeSentDocPdfsForOthers()
    {
        return $this->container['should_include_sent_doc_pdfs_for_others'];
    }

    /**
     * Sets should_include_sent_doc_pdfs_for_others
     *
     * @param bool|null $should_include_sent_doc_pdfs_for_others whether emails sent to recipients include PDF copies of documents the account sends
     *
     * @return self
     */
    public function setShouldIncludeSentDocPdfsForOthers(?bool $should_include_sent_doc_pdfs_for_others)
    {
        if (is_null($should_include_sent_doc_pdfs_for_others)) {
            throw new InvalidArgumentException('non-nullable should_include_sent_doc_pdfs_for_others cannot be null');
        }
        $this->container['should_include_sent_doc_pdfs_for_others'] = $should_include_sent_doc_pdfs_for_others;

        return $this;
    }

    /**
     * Gets should_send_daily_summary
     *
     * @return bool|null
     */
    public function getShouldSendDailySummary()
    {
        return $this->container['should_send_daily_summary'];
    }

    /**
     * Sets should_send_daily_summary
     *
     * @param bool|null $should_send_daily_summary whether to send the account a daily email summarizing outstanding signature requests
     *
     * @return self
     */
    public function setShouldSendDailySummary(?bool $should_send_daily_summary)
    {
        if (is_null($should_send_daily_summary)) {
            throw new InvalidArgumentException('non-nullable should_send_daily_summary cannot be null');
        }
        $this->container['should_send_daily_summary'] = $should_send_daily_summary;

        return $this;
    }

    /**
     * Gets should_send_embedded_signature_conf_emails
     *
     * @return bool|null
     */
    public function getShouldSendEmbeddedSignatureConfEmails()
    {
        return $this->container['should_send_embedded_signature_conf_emails'];
    }

    /**
     * Sets should_send_embedded_signature_conf_emails
     *
     * @param bool|null $should_send_embedded_signature_conf_emails whether to notify the account when it signs a document on a third-party site
     *
     * @return self
     */
    public function setShouldSendEmbeddedSignatureConfEmails(?bool $should_send_embedded_signature_conf_emails)
    {
        if (is_null($should_send_embedded_signature_conf_emails)) {
            throw new InvalidArgumentException('non-nullable should_send_embedded_signature_conf_emails cannot be null');
        }
        $this->container['should_send_embedded_signature_conf_emails'] = $should_send_embedded_signature_conf_emails;

        return $this;
    }

    /**
     * Gets should_send_ordered_sr_email
     *
     * @return bool|null
     */
    public function getShouldSendOrderedSrEmail()
    {
        return $this->container['should_send_ordered_sr_email'];
    }

    /**
     * Sets should_send_ordered_sr_email
     *
     * @param bool|null $should_send_ordered_sr_email whether to notify all parties when an ordered signature request starts
     *
     * @return self
     */
    public function setShouldSendOrderedSrEmail(?bool $should_send_ordered_sr_email)
    {
        if (is_null($should_send_ordered_sr_email)) {
            throw new InvalidArgumentException('non-nullable should_send_ordered_sr_email cannot be null');
        }
        $this->container['should_send_ordered_sr_email'] = $should_send_ordered_sr_email;

        return $this;
    }

    /**
     * Gets should_send_outbound_conf_emails
     *
     * @return bool|null
     */
    public function getShouldSendOutboundConfEmails()
    {
        return $this->container['should_send_outbound_conf_emails'];
    }

    /**
     * Sets should_send_outbound_conf_emails
     *
     * @param bool|null $should_send_outbound_conf_emails whether to notify the account when it signs and sends a document
     *
     * @return self
     */
    public function setShouldSendOutboundConfEmails(?bool $should_send_outbound_conf_emails)
    {
        if (is_null($should_send_outbound_conf_emails)) {
            throw new InvalidArgumentException('non-nullable should_send_outbound_conf_emails cannot be null');
        }
        $this->container['should_send_outbound_conf_emails'] = $should_send_outbound_conf_emails;

        return $this;
    }

    /**
     * Gets template_link_signature_emails_enabled
     *
     * @return bool|null
     */
    public function getTemplateLinkSignatureEmailsEnabled()
    {
        return $this->container['template_link_signature_emails_enabled'];
    }

    /**
     * Sets template_link_signature_emails_enabled
     *
     * @param bool|null $template_link_signature_emails_enabled whether to notify the account when someone signs a document sent by its team through a template link
     *
     * @return self
     */
    public function setTemplateLinkSignatureEmailsEnabled(?bool $template_link_signature_emails_enabled)
    {
        if (is_null($template_link_signature_emails_enabled)) {
            throw new InvalidArgumentException('non-nullable template_link_signature_emails_enabled cannot be null');
        }
        $this->container['template_link_signature_emails_enabled'] = $template_link_signature_emails_enabled;

        return $this;
    }

    /**
     * Gets unset
     *
     * @return string[]|null
     */
    public function getUnset()
    {
        return $this->container['unset'];
    }

    /**
     * Sets unset
     *
     * @param string[]|null $unset Setting names to clear so their values are inherited. A listed name cannot also be set or locked in the same request.
     *
     * @return self
     */
    public function setUnset(?array $unset)
    {
        if (is_null($unset)) {
            throw new InvalidArgumentException('non-nullable unset cannot be null');
        }
        $allowedValues = $this->getUnsetAllowableValues();
        if (array_diff($unset, $allowedValues)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value for 'unset', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }

        $this->container['unset'] = $unset;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    #[ReturnTypeWillChange]
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     */
    #[ReturnTypeWillChange]
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    #[ReturnTypeWillChange]
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_UNESCAPED_SLASHES
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
