<?php
/**
 * EventCallbackRequestEventMetadata
 *
 * PHP version 7.4
 *
 * @category Class
 * @see     https://openapi-generator.tech
 */

/**
 * Dropbox Sign API
 *
 * Dropbox Sign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dropbox\Sign\Model;

use ArrayAccess;
use Dropbox\Sign\ObjectSerializer;
use JsonSerializable;
use ReturnTypeWillChange;

/**
 * EventCallbackRequestEventMetadata Class Doc Comment
 *
 * @category Class
 * @description Specific metadata about the event.
 * @see     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class EventCallbackRequestEventMetadata implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'EventCallbackRequestEventMetadata';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'related_signature_id' => 'string',
        'reported_for_account_id' => 'string',
        'reported_for_app_id' => 'string',
        'event_message' => 'string',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'related_signature_id' => null,
        'reported_for_account_id' => null,
        'reported_for_app_id' => null,
        'event_message' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'related_signature_id' => true,
        'reported_for_account_id' => true,
        'reported_for_app_id' => true,
        'event_message' => true,
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'related_signature_id' => 'related_signature_id',
        'reported_for_account_id' => 'reported_for_account_id',
        'reported_for_app_id' => 'reported_for_app_id',
        'event_message' => 'event_message',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'related_signature_id' => 'setRelatedSignatureId',
        'reported_for_account_id' => 'setReportedForAccountId',
        'reported_for_app_id' => 'setReportedForAppId',
        'event_message' => 'setEventMessage',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'related_signature_id' => 'getRelatedSignatureId',
        'reported_for_account_id' => 'getReportedForAccountId',
        'reported_for_app_id' => 'getReportedForAppId',
        'event_message' => 'getEventMessage',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                           initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('related_signature_id', $data ?? [], null);
        $this->setIfExists('reported_for_account_id', $data ?? [], null);
        $this->setIfExists('reported_for_app_id', $data ?? [], null);
        $this->setIfExists('event_message', $data ?? [], null);
    }

    /**
     * @deprecated use ::init()
     */
    public static function fromArray(array $data): EventCallbackRequestEventMetadata
    {
        return self::init($data);
    }

    /**
     * Attempt to instantiate and hydrate a new instance of this class
     */
    public static function init(array $data): EventCallbackRequestEventMetadata
    {
        /** @var EventCallbackRequestEventMetadata */
        return ObjectSerializer::deserialize(
            $data,
            EventCallbackRequestEventMetadata::class,
        );
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string|int|object|array|mixed $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        return [];
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets related_signature_id
     *
     * @return string|null
     */
    public function getRelatedSignatureId()
    {
        return $this->container['related_signature_id'];
    }

    /**
     * Sets related_signature_id
     *
     * @param string|null $related_signature_id Signature ID for a specific signer. Applicable to `signature_request_signed` and `signature_request_viewed` events.
     *
     * @return self
     */
    public function setRelatedSignatureId(?string $related_signature_id)
    {
        if (is_null($related_signature_id)) {
            array_push($this->openAPINullablesSetToNull, 'related_signature_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('related_signature_id', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['related_signature_id'] = $related_signature_id;

        return $this;
    }

    /**
     * Gets reported_for_account_id
     *
     * @return string|null
     */
    public function getReportedForAccountId()
    {
        return $this->container['reported_for_account_id'];
    }

    /**
     * Sets reported_for_account_id
     *
     * @param string|null $reported_for_account_id account ID the event was reported for
     *
     * @return self
     */
    public function setReportedForAccountId(?string $reported_for_account_id)
    {
        if (is_null($reported_for_account_id)) {
            array_push($this->openAPINullablesSetToNull, 'reported_for_account_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reported_for_account_id', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reported_for_account_id'] = $reported_for_account_id;

        return $this;
    }

    /**
     * Gets reported_for_app_id
     *
     * @return string|null
     */
    public function getReportedForAppId()
    {
        return $this->container['reported_for_app_id'];
    }

    /**
     * Sets reported_for_app_id
     *
     * @param string|null $reported_for_app_id app ID the event was reported for
     *
     * @return self
     */
    public function setReportedForAppId(?string $reported_for_app_id)
    {
        if (is_null($reported_for_app_id)) {
            array_push($this->openAPINullablesSetToNull, 'reported_for_app_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reported_for_app_id', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reported_for_app_id'] = $reported_for_app_id;

        return $this;
    }

    /**
     * Gets event_message
     *
     * @return string|null
     */
    public function getEventMessage()
    {
        return $this->container['event_message'];
    }

    /**
     * Sets event_message
     *
     * @param string|null $event_message message about a declined or failed (due to error) signature flow
     *
     * @return self
     */
    public function setEventMessage(?string $event_message)
    {
        if (is_null($event_message)) {
            array_push($this->openAPINullablesSetToNull, 'event_message');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('event_message', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['event_message'] = $event_message;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    #[ReturnTypeWillChange]
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     */
    #[ReturnTypeWillChange]
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    #[ReturnTypeWillChange]
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_UNESCAPED_SLASHES
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
