generatorName: python
typeMappings: {}
additionalProperties:
  generatorLanguageVersion: ">=3.7"
  packageName: dropbox_sign
  projectName: dropbox-sign
  packageVersion: 1.1.0
  sortModelPropertiesByRequiredFlag: true
  legacyDiscriminatorBehavior: true
  packageAuthor: Dropbox Sign API Team
  packageUrl: https://github.com/hellosign/dropbox-sign-python
  infoName: Official Python SDK for the Dropbox Sign API
files:
  event_callback_helper.mustache:
    templateType: SupportingFiles
    destinationFilename: dropbox_sign/event_callback_helper.py
  VERSION.mustache:
    templateType: SupportingFiles
    destinationFilename: VERSION
globalProperties:
  apiTests: false
  modelTests: false
