generatorName: python
typeMappings:
  "bytearray": "io.IOBase"
additionalProperties:
  generatorLanguageVersion: ">=3.7"
  packageName: dropbox_sign
  projectName: dropbox-sign
  packageVersion: 1.8-dev
  sortModelPropertiesByRequiredFlag: true
  legacyDiscriminatorBehavior: true
  packageAuthor: Dropbox Sign API Team
  packageUrl: https://github.com/hellosign/dropbox-sign-python
  infoName: Official Python SDK for the Dropbox Sign API
  useCustomTemplateCode: true
  licenseCopyrightYear: 2024
  oseg.propertyNamingConvention: snake_case
  oseg.security.api_key.username: YOUR_API_KEY
  oseg.security.oauth2.access_token: YOUR_ACCESS_TOKEN
files:
  dropbox-__init__apis.mustache:
    templateType: SupportingFiles
    destinationFilename: dropbox_sign/apis/__init__.py
  dropbox-event_callback_helper.mustache:
    templateType: SupportingFiles
    destinationFilename: dropbox_sign/event_callback_helper.py
  dropbox-LICENSE.mustache:
    templateType: SupportingFiles
    destinationFilename: LICENSE
  dropbox-VERSION.mustache:
    templateType: SupportingFiles
    destinationFilename: VERSION
globalProperties:
  apiTests: false
  modelTests: false
  removeEnumValuePrefix: true