#!/usr/bin/env bash

# see https://github.com/OpenAPITools/openapi-generator/tree/v7.8.0/modules/openapi-generator/src/main/resources/python

set -e

DIR=$(cd `dirname $0` && pwd)
WORKING_DIR="/app/python"

docker run --rm \
  -v "${DIR}/:/local" \
  openapitools/openapi-generator-cli:v7.8.0 generate \
    -i "/local/openapi-sdk.yaml" \
    -c "/local/openapi-config.yaml" \
    -t "/local/templates" \
    -o "/local/"

printf "Replacing strings ...\n"
docker run --rm \
  -v "${DIR}:${WORKING_DIR}" \
  -w "${WORKING_DIR}" \
  perl bash ./bin/replace
