#!/usr/bin/env bash

# see https://github.com/OpenAPITools/openapi-generator/tree/v7.8.0/modules/openapi-generator/src/main/resources/php

set -e

DIR=$(cd `dirname $0` && pwd)
WORKING_DIR="/app/php"

if [[ -n "$GITHUB_ACTIONS" ]]; then
  printf "\nLogging in to docker.com ...\n"
  echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
fi

# cleanup
rm -f "${DIR}/src/Api/"*.php
rm -f "${DIR}/src/Model/"*.php

docker run --rm \
  -v "${DIR}/:/local" \
  -v "${DIR}/openapi-sdk.yaml:/local/openapi-sdk.yaml" \
  openapitools/openapi-generator-cli:v7.12.0 generate \
    -i "/local/openapi-sdk.yaml" \
    -c "/local/openapi-config.yaml" \
    -t "/local/templates" \
    -o "/local/"

printf "\nInstalling composer dependencies ...\n"
mkdir -p "${DIR}/vendor"
bash "${DIR}/bin/php" composer install
printf "\n"

printf "Adding examples to Docs ...\n"
bash "${DIR}/bin/php-8" ./bin/generate-examples.php

printf "Running php-cs-fixer ...\n"
bash "${DIR}/bin/php-8" ./vendor/bin/php-cs-fixer fix --verbose

printf "Replacing strings ...\n"
docker run --rm \
  -v "${DIR}:${WORKING_DIR}" \
  -w "${WORKING_DIR}" \
  perl bash ./bin/replace

printf "Scanning for prohibited keywords ...\n"
docker run --rm \
  -v "${DIR}:${WORKING_DIR}" \
  -w "${WORKING_DIR}" \
  perl bash ./bin/scan_for

printf "Adding old-style constant names ...\n"
bash "${DIR}/bin/php-8" ./bin/copy-constants.php

# avoid docker messing with permissions
if [[ -z "$GITHUB_ACTIONS" ]]; then
  chmod 644 "${DIR}/README.md"
  find "${DIR}/docs/" -type f -exec chmod 644 {} \;
  find "${DIR}/examples/" -type f -exec chmod 644 {} \;
  find "${DIR}/test_fixtures/" -type f -exec chmod 644 {} \;
  find "${DIR}/src/" -type f -exec chmod 644 {} \;
fi

printf "Running unit tests ...\n"
PHP_USE_NATIVE=0 bash "${DIR}/bin/php" ./vendor/bin/phpunit
printf "\n\n"

printf "Success!\n"
