curl -X POST 'https://api.hellosign.com/v3/signature_request/create_embedded_with_template' \
  -u 'YOUR_API_KEY:' \
  -F 'client_id=YOUR_CLIENT_ID' \
  -F 'template_ids[]=c26b8a16784a872da37ea946b9ddec7c1e11dff6' \
  -F 'subject=Purchase Order' \
  -F 'message=Glad we could come to an agreement.' \
  -F 'signers[0][role]=Client' \
  -F 'signers[0][name]=George' \
  -F 'signers[0][email_address]=george@example.com' \
  -F 'signing_options[draw]=1' \
  -F 'signing_options[type]=1' \
  -F 'signing_options[upload]=1' \
  -F 'signing_options[phone]=1' \
  -F 'signing_options[default_type]=draw' \
  -F 'test_mode=1'
