curl -X POST 'https://api.hellosign.com/v3/unclaimed_draft/create' \
  -u 'YOUR_API_KEY:' \
  -F 'type=request_signature' \
  -F 'files[0]=@mutual-NDA-example.pdf' \
  -F 'subject=The NDA we talked about' \
  -F 'message=Please sign this NDA and then we can discuss more. Let me know if you have any questions.' \
  -F 'signers[0][email_address]=jack@example.com' \
  -F 'signers[0][name]=Jack' \
  -F 'signers[0][order]=0' \
  -F 'signers[1][email_address]=jill@example.com' \
  -F 'signers[1][name]=Jill' \
  -F 'signers[1][order]=1' \
  -F 'cc_email_addresses[0]=lawyer1@dropboxsign.com' \
  -F 'cc_email_addresses[1]=lawyer2@dropboxsign.com' \
  -F 'metadata[0][custom_id]=1234' \
  -F 'metadata[0][custom_text]=NDA #9' \
  -F 'signing_options[draw]=1' \
  -F 'signing_options[type]=1' \
  -F 'signing_options[upload]=1' \
  -F 'signing_options[phone]=0' \
  -F 'signing_options[default_type]=draw' \
  -F 'field_options[date_format]=DD - MM - YYYY' \
  -F 'test_mode=1'
