generatorName: csharp
additionalProperties:
  clientPackage: Client
  packageName: Dropbox.Sign
  packageAuthors: Dropbox Sign API Team
  packageCompany: Dropbox Sign API Team
  packageCopyright: Dropbox 2024
  packageDescription: Client library for using the Dropbox Sign API
  packageVersion: 1.5-dev
  packageTitle: Dropbox Sign .Net SDK
  sortModelPropertiesByRequiredFlag: true
  optionalEmitDefaultValues: true
  targetFramework: net6.0
  packageGuid: "{F8C8232D-7020-4603-8E04-18D060AE530B}"
  legacyDiscriminatorBehavior: true
  useCustomTemplateCode: true
files:
  EventCallbackHelper.cs:
    templateType: SupportingFiles
    destinationFilename: src/Dropbox.Sign/EventCallbackHelper.cs
  VERSION.mustache:
    templateType: SupportingFiles
    destinationFilename: VERSION
globalProperties:
  apiTests: false
  modelTests: false
