generatorName: csharp
additionalProperties:
  clientPackage: Client
  packageName: Dropbox.Sign
  packageAuthors: Dropbox Sign API Team
  packageCompany: Dropbox Sign API Team
  packageCopyright: Dropbox 2024
  packageDescription: Client library for using the Dropbox Sign API
  packageVersion: 1.8-dev
  packageTitle: Dropbox Sign .Net SDK
  sortModelPropertiesByRequiredFlag: true
  optionalEmitDefaultValues: true
  targetFramework: net8.0
  library: restsharp
  packageGuid: "{F8C8232D-7020-4603-8E04-18D060AE530B}"
  legacyDiscriminatorBehavior: true
  useCustomTemplateCode: true
  licenseCopyrightYear: 2024
  oseg.namespace: Dropbox.SignSandbox
  oseg.packageGuid: "{7045D429-F203-4317-A29F-FB9FD34B7FF9}"
  oseg.security.api_key.username: YOUR_API_KEY
  oseg.security.oauth2.access_token: YOUR_ACCESS_TOKEN
files:
  dropbox-EventCallbackHelper.cs:
    templateType: SupportingFiles
    destinationFilename: src/Dropbox.Sign/EventCallbackHelper.cs
  dropbox-LICENSE.mustache:
    templateType: SupportingFiles
    destinationFilename: LICENSE
  dropbox-VERSION.mustache:
    templateType: SupportingFiles
    destinationFilename: VERSION
globalProperties:
  apiTests: false
  modelTests: false
  removeEnumValuePrefix: true
