#!/usr/bin/env bash

# see https://github.com/OpenAPITools/openapi-generator/tree/v7.8.0/modules/openapi-generator/src/main/resources/csharp

set -e

DIR=$(cd `dirname $0` && pwd)
WORKING_DIR="/app/dotnet"

if [[ -n "$GITHUB_ACTIONS" ]]; then
  printf "\nLogging in to docker.com ...\n"
  echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
fi

# cleanup
rm -f "${DIR}/src/Dropbox.Sign/Api/"*.cs
rm -f "${DIR}/src/Dropbox.Sign/Model/"*.cs

docker run --rm \
  -v "${DIR}/:/local" \
  openapitools/openapi-generator-cli:v7.8.0 generate \
    -i "/local/openapi-sdk.yaml" \
    -c "/local/openapi-config.yaml" \
    -t "/local/templates" \
    -o "/local/"

bash "${DIR}/bin/dotnet" dotnet format ./

printf "\nInstalling composer dependencies ...\n"
mkdir -p "${DIR}/vendor"
bash "${DIR}/bin/php" composer install
printf "\n"

printf "Adding examples to Docs ...\n"
bash "${DIR}/bin/php" ./bin/generate-examples.php

printf "Replacing strings ...\n"
docker run --rm \
  -v "${DIR}:${WORKING_DIR}" \
  -w "${WORKING_DIR}" \
  perl bash ./bin/replace

printf "Scanning for prohibited keywords ...\n"
docker run --rm \
  -v "${DIR}:${WORKING_DIR}" \
  -w "${WORKING_DIR}" \
  perl bash ./bin/scan_for

# avoid docker messing with permissions
if [[ -z "$GITHUB_ACTIONS" ]]; then
  chmod 644 "${DIR}/README.md"
  find "${DIR}/docs/" -type f -exec chmod 644 {} \;
  find "${DIR}/examples/" -type f -exec chmod 644 {} \;
  find "${DIR}/test_fixtures/" -type f -exec chmod 644 {} \;
  find "${DIR}/src/" -type f -exec chmod 644 {} \;
fi

printf "Running tests ...\n"
bash "${DIR}/bin/dotnet" dotnet test src/Dropbox.Sign.Test/

printf "Success!\n"
