#!/usr/bin/env bash

# see https://github.com/OpenAPITools/openapi-generator/tree/v7.7.0/modules/openapi-generator/src/main/resources/csharp

set -e

DIR=$(cd `dirname $0` && pwd)
WORKING_DIR="/app/dotnet"

docker run --rm \
  -v "${DIR}/:/local" \
  openapitools/openapi-generator-cli:v7.7.0 generate \
    -i "/local/openapi-sdk.yaml" \
    -c "/local/openapi-config.yaml" \
    -t "/local/templates" \
    -o "/local/"
