/*
 * Dropbox Sign API
 *
 * Dropbox Sign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Dropbox.Sign.Client.OpenAPIDateConverter;

namespace Dropbox.Sign.Model
{
    /// <summary>
    /// _t__TeamResponse::DESCRIPTION
    /// </summary>
    [DataContract(Name = "TeamResponse")]
    [JsonObject(ItemNullValueHandling = NullValueHandling.Ignore)]
    public partial class TeamResponse : IEquatable<TeamResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TeamResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TeamResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TeamResponse" /> class.
        /// </summary>
        /// <param name="name">_t__Team::NAME.</param>
        /// <param name="accounts">accounts.</param>
        /// <param name="invitedAccounts">_t__Team::INVITED_ACCOUNTS.</param>
        /// <param name="invitedEmails">_t__Team::INVITED_EMAILS.</param>
        public TeamResponse(string name = default(string), List<AccountResponse> accounts = default(List<AccountResponse>), List<AccountResponse> invitedAccounts = default(List<AccountResponse>), List<string> invitedEmails = default(List<string>))
        {

            this.Name = name;
            this.Accounts = accounts;
            this.InvitedAccounts = invitedAccounts;
            this.InvitedEmails = invitedEmails;
        }

        /// <summary>
        /// Attempt to instantiate and hydrate a new instance of this class
        /// </summary>
        /// <param name="jsonData">String of JSON data representing target object</param>
        public static TeamResponse Init(string jsonData)
        {
            var obj = JsonConvert.DeserializeObject<TeamResponse>(jsonData);

            if (obj == null)
            {
                throw new Exception("Unable to deserialize JSON to instance of TeamResponse");
            }

            return obj;
        }

        /// <summary>
        /// _t__Team::NAME
        /// </summary>
        /// <value>_t__Team::NAME</value>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Accounts
        /// </summary>
        [DataMember(Name = "accounts", EmitDefaultValue = true)]
        public List<AccountResponse> Accounts { get; set; }

        /// <summary>
        /// _t__Team::INVITED_ACCOUNTS
        /// </summary>
        /// <value>_t__Team::INVITED_ACCOUNTS</value>
        [DataMember(Name = "invited_accounts", EmitDefaultValue = true)]
        public List<AccountResponse> InvitedAccounts { get; set; }

        /// <summary>
        /// _t__Team::INVITED_EMAILS
        /// </summary>
        /// <value>_t__Team::INVITED_EMAILS</value>
        [DataMember(Name = "invited_emails", EmitDefaultValue = true)]
        public List<string> InvitedEmails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TeamResponse {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Accounts: ").Append(Accounts).Append("\n");
            sb.Append("  InvitedAccounts: ").Append(InvitedAccounts).Append("\n");
            sb.Append("  InvitedEmails: ").Append(InvitedEmails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TeamResponse);
        }

        /// <summary>
        /// Returns true if TeamResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TeamResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TeamResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) &&
                (
                    this.Accounts == input.Accounts ||
                    this.Accounts != null &&
                    input.Accounts != null &&
                    this.Accounts.SequenceEqual(input.Accounts)
                ) &&
                (
                    this.InvitedAccounts == input.InvitedAccounts ||
                    this.InvitedAccounts != null &&
                    input.InvitedAccounts != null &&
                    this.InvitedAccounts.SequenceEqual(input.InvitedAccounts)
                ) &&
                (
                    this.InvitedEmails == input.InvitedEmails ||
                    this.InvitedEmails != null &&
                    input.InvitedEmails != null &&
                    this.InvitedEmails.SequenceEqual(input.InvitedEmails)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Accounts != null)
                {
                    hashCode = (hashCode * 59) + this.Accounts.GetHashCode();
                }
                if (this.InvitedAccounts != null)
                {
                    hashCode = (hashCode * 59) + this.InvitedAccounts.GetHashCode();
                }
                if (this.InvitedEmails != null)
                {
                    hashCode = (hashCode * 59) + this.InvitedEmails.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
        public List<OpenApiType> GetOpenApiTypes()
        {
            var types = new List<OpenApiType>();
            types.Add(new OpenApiType()
            {
                Name = "name",
                Property = "Name",
                Type = "string",
                Value = Name,
            });
            types.Add(new OpenApiType()
            {
                Name = "accounts",
                Property = "Accounts",
                Type = "List<AccountResponse>",
                Value = Accounts,
            });
            types.Add(new OpenApiType()
            {
                Name = "invited_accounts",
                Property = "InvitedAccounts",
                Type = "List<AccountResponse>",
                Value = InvitedAccounts,
            });
            types.Add(new OpenApiType()
            {
                Name = "invited_emails",
                Property = "InvitedEmails",
                Type = "List<string>",
                Value = InvitedEmails,
            });

            return types;
        }
    }

}
