generatorName: typescript-node
typeMappings: {}
additionalProperties:
  npmName: "@dropbox/sign"
  npmVersion: 1.9-dev
  supportsES6: true
  apiDocPath: ./docs/api
  modelDocPath: ./docs/model
  sortModelPropertiesByRequiredFlag: true
  useCustomTemplateCode: true
  licenseCopyrightYear: 2024
  oseg.npmName: "@dropbox/sign-sandbox"
  oseg.printApiCallProperty: true
  oseg.security.api_key.username: YOUR_API_KEY
  oseg.security.oauth2.access_token: YOUR_ACCESS_TOKEN
files:
  dropbox-npmignore:
    templateType: SupportingFiles
    destinationFilename: .npmignore
  dropbox-api-doc.mustache:
    templateType: APIDocs
    destinationFilename: .md
  dropbox-model-doc.mustache:
    templateType: ModelDocs
    destinationFilename: .md
  dropbox-README.mustache:
    templateType: SupportingFiles
    destinationFilename: README.md
  dropbox-eventCallbackHelper.mustache:
    templateType: SupportingFiles
    destinationFilename: model/eventCallbackHelper.ts
  dropbox-LICENSE.mustache:
    templateType: SupportingFiles
    destinationFilename: LICENSE
  dropbox-VERSION.mustache:
    templateType: SupportingFiles
    destinationFilename: VERSION
  dropbox-api-index.mustache:
    templateType: SupportingFiles
    destinationFilename: api/index.ts
  dropbox-model-index.mustache:
    templateType: SupportingFiles
    destinationFilename: model/index.ts
  dropbox-prettierrc.cjs:
    templateType: SupportingFiles
    destinationFilename: .prettierrc.cjs
globalProperties:
  apiTests: false
  modelTests: false
