generatorName: typescript-node
typeMappings: {}
additionalProperties:
  npmName: "@dropbox/sign"
  npmVersion: 1.1.1
  supportsES6: true
  apiDocPath: ./docs/api
  modelDocPath: ./docs/model
  sortModelPropertiesByRequiredFlag: true
files:
  npmignore:
    templateType: SupportingFiles
    destinationFilename: .npmignore
  api-doc.mustache:
    templateType: APIDocs
    destinationFilename: .md
  model-doc.mustache:
    templateType: ModelDocs
    destinationFilename: .md
  README.mustache:
    templateType: SupportingFiles
    destinationFilename: README.md
  eventCallbackHelper.mustache:
    templateType: SupportingFiles
    destinationFilename: model/eventCallbackHelper.ts
  VERSION.mustache:
    templateType: SupportingFiles
    destinationFilename: VERSION
  api-index.mustache:
    templateType: SupportingFiles
    destinationFilename: api/index.ts
  model-index.mustache:
    templateType: SupportingFiles
    destinationFilename: model/index.ts
globalProperties:
  apiTests: false
  modelTests: false
