import { AttributeTypeMap } from "./";
import { SignatureRequestResponseAttachment } from "./signatureRequestResponseAttachment";
import { SignatureRequestResponseCustomFieldBase } from "./signatureRequestResponseCustomFieldBase";
import { SignatureRequestResponseDataBase } from "./signatureRequestResponseDataBase";
import { SignatureRequestResponseSignatures } from "./signatureRequestResponseSignatures";
export declare class SignatureRequestResponse {
    "testMode"?: boolean;
    "signatureRequestId"?: string;
    "requesterEmailAddress"?: string | null;
    "title"?: string;
    "originalTitle"?: string;
    "subject"?: string;
    "message"?: string;
    "metadata"?: object;
    "createdAt"?: number;
    "expiresAt"?: number | null;
    "isComplete"?: boolean;
    "isDeclined"?: boolean;
    "hasError"?: boolean;
    "filesUrl"?: string;
    "signingUrl"?: string | null;
    "detailsUrl"?: string;
    "ccEmailAddresses"?: Array<string>;
    "signingRedirectUrl"?: string | null;
    "finalCopyUri"?: string | null;
    "templateIds"?: Array<string> | null;
    "customFields"?: Array<SignatureRequestResponseCustomFieldBase>;
    "attachments"?: Array<SignatureRequestResponseAttachment>;
    "responseData"?: Array<SignatureRequestResponseDataBase>;
    "signatures"?: Array<SignatureRequestResponseSignatures>;
    "bulkSendJobId"?: string | null;
    static discriminator: string | undefined;
    static attributeTypeMap: AttributeTypeMap;
    static getAttributeTypeMap(): AttributeTypeMap;
    static init(data: any): SignatureRequestResponse;
}
