import { AttributeTypeMap } from "./";
import { SignatureRequestResponseAttachment } from "./signatureRequestResponseAttachment";
import { TemplateResponseAccount } from "./templateResponseAccount";
import { TemplateResponseCCRole } from "./templateResponseCCRole";
import { TemplateResponseDocument } from "./templateResponseDocument";
import { TemplateResponseDocumentCustomFieldBase } from "./templateResponseDocumentCustomFieldBase";
import { TemplateResponseDocumentFormFieldBase } from "./templateResponseDocumentFormFieldBase";
import { TemplateResponseSignerRole } from "./templateResponseSignerRole";
export declare class TemplateResponse {
    "templateId": string;
    "title": string;
    "message": string;
    "isCreator": boolean;
    "canEdit": boolean;
    "isLocked": boolean;
    "metadata": object;
    "signerRoles": Array<TemplateResponseSignerRole>;
    "ccRoles": Array<TemplateResponseCCRole>;
    "documents": Array<TemplateResponseDocument>;
    "accounts": Array<TemplateResponseAccount>;
    "attachments": Array<SignatureRequestResponseAttachment>;
    "updatedAt"?: number;
    "isEmbedded"?: boolean | null;
    "customFields"?: Array<TemplateResponseDocumentCustomFieldBase> | null;
    "namedFormFields"?: Array<TemplateResponseDocumentFormFieldBase> | null;
    static discriminator: string | undefined;
    static attributeTypeMap: AttributeTypeMap;
    static getAttributeTypeMap(): AttributeTypeMap;
    static init(data: any): TemplateResponse;
}
