/*
 * Dropbox Sign API
 * Dropbox Sign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dropbox.sign.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.dropbox.sign.JSON;


import com.dropbox.sign.ApiException;
/**
 * Optional certification types to be applied to your Signature Request after completion.  After all parties have signed and completed identity verification (if &#x60;is_eid&#x60; is &#x60;true&#x60;), your document&#39;s hash will be sent to the specified certificate authority for archiving and integrity verification.  At this time only a single certification type can be selected per Signature Request.
 */
@ApiModel(description = "Optional certification types to be applied to your Signature Request after completion.  After all parties have signed and completed identity verification (if `is_eid` is `true`), your document's hash will be sent to the specified certificate authority for archiving and integrity verification.  At this time only a single certification type can be selected per Signature Request.")
@JsonPropertyOrder({
    SubCertificationTypes.JSON_PROPERTY_NOM151
})
@JsonIgnoreProperties(ignoreUnknown=true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SubCertificationTypes {
  public static final String JSON_PROPERTY_NOM151 = "nom_151";
  private Boolean nom151 = false;

  public SubCertificationTypes() { 
  }

  /**
   * Attempt to instantiate and hydrate a new instance of this class
   * @param jsonData String of JSON data representing target object
   */
  static public SubCertificationTypes init(String jsonData) throws Exception {
    return new ObjectMapper().readValue(jsonData, SubCertificationTypes.class);
  }

  static public SubCertificationTypes init(HashMap data) throws Exception {
    return new ObjectMapper().readValue(
      new ObjectMapper().writeValueAsString(data),
      SubCertificationTypes.class
    );
  }

  public SubCertificationTypes nom151(Boolean nom151) {
    this.nom151 = nom151;
    return this;
  }

   /**
   * NOM 151, or Normativa 151, is a certificate which verifies the integrity of an electronically signed document in compliance with Mexican regulations.
   * @return nom151
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "NOM 151, or Normativa 151, is a certificate which verifies the integrity of an electronically signed document in compliance with Mexican regulations.")
  @JsonProperty(JSON_PROPERTY_NOM151)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNom151() {
    return nom151;
  }


  @JsonProperty(JSON_PROPERTY_NOM151)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNom151(Boolean nom151) {
    this.nom151 = nom151;
  }


  /**
   * Return true if this SubCertificationTypes object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubCertificationTypes subCertificationTypes = (SubCertificationTypes) o;
    return Objects.equals(this.nom151, subCertificationTypes.nom151);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nom151);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubCertificationTypes {\n");
    sb.append("    nom151: ").append(toIndentedString(nom151)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  public Map<String, Object> createFormData() throws ApiException {
    Map<String, Object> map = new HashMap<>();
    boolean fileTypeFound = false;
    try {
    if (nom151 != null) {
        if (isFileTypeOrListOfFiles(nom151)) {
            fileTypeFound = true;
        }

        if (nom151.getClass().equals(java.io.File.class) ||
            nom151.getClass().equals(Integer.class) ||
            nom151.getClass().equals(String.class) ||
            nom151.getClass().isEnum()) {
            map.put("nom_151", nom151);
        } else if (isListOfFile(nom151)) {
            for(int i = 0; i< getListSize(nom151); i++) {
                map.put("nom_151[" + i + "]", getFromList(nom151, i));
            }
        }
        else {
            map.put("nom_151", JSON.getDefault().getMapper().writeValueAsString(nom151));
        }
    }
    } catch (Exception e) {
        throw new ApiException(e);
    }

    return fileTypeFound ? map : new HashMap<>();
  }

  private boolean isFileTypeOrListOfFiles(Object obj) throws Exception {
    return obj.getClass().equals(java.io.File.class) || isListOfFile(obj);
  }

  private boolean isListOfFile(Object obj) throws Exception {
      return obj instanceof java.util.List && !isListEmpty(obj) && getFromList(obj, 0) instanceof java.io.File;
  }

  private boolean isListEmpty(Object obj) throws Exception {
    return (boolean) Class.forName(java.util.List.class.getName()).getMethod("isEmpty").invoke(obj);
  }

  private Object getFromList(Object obj, int index) throws Exception {
    return Class.forName(java.util.List.class.getName()).getMethod("get", int.class).invoke(obj, index);
  }

  private int getListSize(Object obj) throws Exception {
    return (int) Class.forName(java.util.List.class.getName()).getMethod("size").invoke(obj);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

