/*
Dropbox Sign API

Testing ApiAppAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ApiAppAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ApiAppAPIService ApiAppCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ApiAppAPI.ApiAppCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApiAppAPIService ApiAppDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var clientId string

		httpRes, err := apiClient.ApiAppAPI.ApiAppDelete(context.Background(), clientId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApiAppAPIService ApiAppGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var clientId string

		resp, httpRes, err := apiClient.ApiAppAPI.ApiAppGet(context.Background(), clientId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApiAppAPIService ApiAppList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ApiAppAPI.ApiAppList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApiAppAPIService ApiAppUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var clientId string

		resp, httpRes, err := apiClient.ApiAppAPI.ApiAppUpdate(context.Background(), clientId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
